name: Convert Markdown to HTML

on:
  push:
    branches:
      - only-md

jobs:
  convert-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: only-md

      - name: Get changed .md files
        id: changed-md-files
        run: |
          # Get the list of added or modified .md files in the latest commit
          CHANGED_FILES=$(git diff --name-only --diff-filter=AM HEAD^ HEAD | grep '\.md$')
          echo "Changed or added .md files: $CHANGED_FILES"
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Check if there are .md files to process
        id: check-md-files
        run: |
          if [ -z "${{ steps.changed-md-files.outputs.files }}" ]; then
            echo "No .md files to process. Exiting."
            echo "::set-output name=has_files::false"
          else
            echo "Found .md files to process."
            echo "::set-output name=has_files::true"
          fi

      - name: Install pandoc
        if: steps.check-md-files.outputs.has_files == 'true'
        run: sudo apt-get install -y pandoc

      - name: Convert .md files to HTML
        if: steps.check-md-files.outputs.has_files == 'true'
        run: |
          for file in ${{ steps.changed-md-files.outputs.files }}; do
            echo "Converting $file to HTML..."
            pandoc -s --css="/styles/styles.css" "$file" -o "${file%.md}.html" --mathml
          done

      - name: Checkout main branch
        if: steps.check-md-files.outputs.has_files == 'true'
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Commit HTML files to main branch
        if: steps.check-md-files.outputs.has_files == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-generated HTML files from .md files in only-md branch"
          git push origin main
