name: Convert Markdown to HTML

on:
  push:
    branches:
      - only-md

jobs:
  convert-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: only-md

      - name: Install Fish shell
        run: sudo apt-get install -y fish

      - name: Get changed .md files
        id: changed-md-files
        shell: fish
        run: |
          # Get the list of added or modified .md files in the latest commit
          set CHANGED_FILES (git diff --name-only --diff-filter=AM HEAD^ HEAD | grep '\.md$')
          echo "Changed or added .md files: $CHANGED_FILES"
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Check if there are .md files to process
        id: check-md-files
        shell: fish
        run: |
          if test -z "${{ steps.changed-md-files.outputs.files }}"
            echo "No .md files to process. Exiting."
            echo "::set-output name=has_files::false"
          else
            echo "Found .md files to process."
            echo "::set-output name=has_files::true"
          end

      - name: Install pandoc
        if: steps.check-md-files.outputs.has_files == 'true'
        run: sudo apt-get install -y pandoc

      - name: Convert .md files to HTML
        if: steps.check-md-files.outputs.has_files == 'true'
        shell: fish
        run: |
          for file in (echo ${{ steps.changed-md-files.outputs.files }} | tr ' ' '\n')
            # Get the directory of the .md file
            set dir (dirname "$file")
            echo "Processing $file in directory $dir..."
            # Navigate to the directory
            cd "$dir"
            # Convert the .md file to index.html
            pandoc -s --css="/styles/styles.css" (basename "$file") -o index.html --mathml
            # Return to the root directory
            cd -
          end

      - name: Checkout main branch
        if: steps.check-md-files.outputs.has_files == 'true'
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Merge only-md branch into main
        if: steps.check-md-files.outputs.has_files == 'true'
        shell: fish
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin only-md
          git merge origin/only-md --no-ff -m "Merge only-md branch into main"

      - name: Commit HTML files to main branch
        if: steps.check-md-files.outputs.has_files == 'true'
        shell: fish
        run: |
          git add .
          git commit -m "Auto-generated HTML files from .md files in only-md branch"
          git push origin main
