name: Convert Markdown to HTML

on:
  push:
    branches:
      - only-md

jobs:
  convert_md_to_html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure at least one previous commit is available

      - name: Detect changed .md files
        id: changed-md
        run: |
          echo "Checking for modified Markdown files..."
          CHANGED_FILES=$(git diff --name-only --diff-filter=MA HEAD^ HEAD | grep '\.md$' || true)
          echo "Detected files: $CHANGED_FILES"
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No new or modified Markdown files. Exiting workflow."
            exit 0
          fi
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Convert Markdown to HTML
        run: |
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            dir=$(dirname "$file")
            echo "Processing: $file in directory: $dir"
            cd "$dir" || exit 1
            pandoc -s --css="/styles/styles.css" "$(basename "$file")" -o index.html --mathml
            cd - > /dev/null || exit 1
          done <<< "$CHANGED_FILES"

      - name: Debug: List files after conversion
        run: ls -R

      - name: Commit and push changes to main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout main || git checkout -b main
          git merge --allow-unrelated-histories -X theirs only-md -m "Merge branch 'only-md' into main"

          echo "Checking git status before committing..."
          git status

          git add .
          git commit -m "Generated HTML files from updated Markdown" || echo "No changes to commit"
          git push origin main || echo "Push failed"
